# Generated by Django 4.0 on 2022-01-08 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_dept',
            field=models.CharField(help_text='Phone Number Format: +254722399744', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Health Department Contact'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Neighbourhood Location'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Neighbourhood Name'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(default=0, verbose_name='Neighbourhood Occupants'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_dept',
            field=models.CharField(help_text='Phone Number Format: +254722399744', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Police Department Contact'),
        ),
    ]
