# Generated by Django 4.0 on 2022-01-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_profile_email_profile_neighbourhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(null=True, verbose_name='Neighbourhood Occupants'),
        ),
    ]
