# Generated by Django 4.0 on 2022-01-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('neighbourhood', '0004_alter_neighbourhood_occupants'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
