# Generated by Django 4.0 on 2022-01-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_business_business_email_business_business_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile_user',
        ),
    ]
