# Generated by Django 4.0 on 2022-01-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_rename_user_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_neighbourhood', to='neighbourhood.neighbourhood'),
        ),
    ]
