# Generated by Django 4.0 on 2022-01-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0007_alter_profile_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_business', to='neighbourhood.neighbourhood'),
        ),
    ]
