# Generated by Django 4.0 on 2022-01-09 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0009_post_post_content_post_post_neighbourhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
